### ISSUE TITLE
I want version 1.1, but i only get version 1.0.

### ISSUE THREAD

**Issue by Deletedaccount1928** [kregerl/BakkesKBMOverlay#3]
I tried to use the plugin manager, but it dosent work for me. I most likely am doing something wrong. I would appreciate some help on this :)

A small video where you @kregerl show it would be amazing! 👍

**Comment by maggaou** [comment]
The plugin is released in Bakkesplugins.com. See https://bakkesplugins.com/plugins/view/388. In the website you can install plugins by pressing the "install with BakkesMod".

**Comment by Deletedaccount1928** [comment]
That's what i did. Then i open the plugin manager and enable it, but i get version 1.0, and not 1.1. I primary want the version 1.1 for the feature transparency for more visibility. 

I attached a video here where you can see what i see.

Would love some help on this. Maybe  you @maggaou can show me a video of what you see, maybe its just bugged for me.

**Comment by maggaou** [comment]
Just open command line and then type k. You should see the two parameters. To set them, just type name <space> value. I think by default you press F2 to open the command line.

**Comment by Deletedaccount1928** [comment]
I just cant get it to work. I know am asking for much, but can you attach a video where you show what to exactly do? @maggaou

**Comment by maggaou** [comment]
What you want to do exactly? If you want to stream your gameplay with KBM overlay, then you can use OBS + [Input Overlay](https://obsproject.com/forum/resources/input-overlay.552/). I'm not sure what was the original use case thought by the author of this plugin, but definitely my issue #1 would make the plugin more useful.

**Comment by Deletedaccount1928** [comment]
I dont want to stream my gameplay, i just want the KBM overlay for clips that i post on tiktok. Unfortunately i dont know how to get version 1.1.

**Comment by maggaou** [comment]
Are you able to open the console? You can find cvars like sv_training_enabled by typing sv. The version number that plugin manager reports is usually inaccurate: you can have version 1.1 even if the plugin manager says otherwise. The most accurate version information is always found on the project page itself.

**Comment by Deletedaccount1928** [comment]
What do you mean by opening the console?

**Comment by maggaou** [comment]
Press BM icon on the taskbar, then file, open BM folder. Go to cfg folder, then open binds.cfg using Notepad. Make sure that there is the following line:
`bind F2 "togglemenu console2;`
You could have some other key instead of F2 (I use F2). If you make changes to the file, remember to save.

Open RL and wait BM to inject. Go to plugin manager and make sure you have the plugin enabled. Press F2 to open the console. Write "k" to discover that you can set kbmscale and kbmtransparency variables. To set kbmscale, write kbms then press tab, input your value and press enter. To close the command line window, press esc.

**Comment by Deletedaccount1928** [comment]
This really made my day man, thanks @maggaou for all the help. Everything works perfectly now <3.
